workflows:
  build:
    name: Build APK
    environment:
      flutter: stable
      node: "14.0.0"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build the app
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
